name: slack

on:
  pull_request:
    branches:
      - main
    types: [review_requested]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: action-slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,message,author # action,eventName,ref,workflow,job,took 추가할 수 있음
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
